spring:
  application:
    name: elastic-knn

devglan:
  elastic:
    url: https://localhost:9200
    #apiKey: YOUR_BASE64_ENCODED_API_KEY
    username: elastic
    #.\bin\elasticsearch-reset-password.bat -u elastic --url https://localhost:9200
    password: ojQPn8zI+5f4o1_m-oGz
    similarityThreshold: "60%"
    minScore: 0.91
    modelId: multilingual-e5-small
    field: content_vector
    indices:
      - semantic-docs
